name: Executar Importador da Carteira

on:
  schedule:
    - cron: '0 13,15,18,22 * * *'  # Horários UTC = 10h, 12h, 15h, 19h BRT
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install gspread pandas gspread-formatting google-auth

      - name: Criar arquivo de credenciais
        run: |
          echo "${{ secrets.CREDENCIAIS_JSON }}" > credenciais.json

      - name: Executar script importador
        run: |
          python importador_carteira.py
