name: Importador Carteira - Agendado

on:
  schedule:
    - cron: '0 13 * * *'  # 10h BRT
    - cron: '0 15 * * *'  # 12h BRT
    - cron: '0 18 * * *'  # 15h BRT
    - cron: '0 22 * * *'  # 19h BRT
  workflow_dispatch:

jobs:
  executar-importador:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client gspread-formatting

      - name: Criar arquivo de credenciais
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credenciais.json

      - name: Executar script Python
        run: python importador_carteira.py
        Criar workflow de agendamento
