name: Agendador Importador

on:
  schedule:
    - cron: '0 13 * * *'  # 10h BRT (13 UTC)
    - cron: '0 15 * * *'  # 12h BRT (15 UTC)
    - cron: '0 18 * * *'  # 15h BRT (18 UTC)
    - cron: '0 22 * * *'  # 19h BRT (22 UTC)
  workflow_dispatch:

jobs:
  executar-importacao:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          pip install gspread pandas gspread-formatting oauth2client

      - name: Criar credenciais
        run: |
          echo "${{ secrets.CREDENCIAIS_JSON }}" > credenciais.json

      - name: Executar script
        run: python importador_carteira.py
